// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sync.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Fuzzilli_Protobuf_LogMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// UUID of the original instance
  public var origin: String = String()

  public var level: UInt32 = 0

  public var label: String = String()

  public var content: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Fuzzilli_Protobuf_FuzzerState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var corpus: Data = Data()

  public var evaluatorState: Data = Data()

  public var isWasmEnabled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Fuzzilli_Protobuf_Statistics: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// The total number of samples produced.
  public var totalSamples: UInt64 {
    get {return _storage._totalSamples}
    set {_uniqueStorage()._totalSamples = newValue}
  }

  //// The number of valid samples produced.
  public var validSamples: UInt64 {
    get {return _storage._validSamples}
    set {_uniqueStorage()._validSamples = newValue}
  }

  //// The number of intersting samples produced.
  public var interestingSamples: UInt64 {
    get {return _storage._interestingSamples}
    set {_uniqueStorage()._interestingSamples = newValue}
  }

  //// The number of timed-out samples produced.
  public var timedOutSamples: UInt64 {
    get {return _storage._timedOutSamples}
    set {_uniqueStorage()._timedOutSamples = newValue}
  }

  //// The number of crashes found.
  public var crashingSamples: UInt64 {
    get {return _storage._crashingSamples}
    set {_uniqueStorage()._crashingSamples = newValue}
  }

  //// The total number of program executions.
  public var totalExecs: UInt64 {
    get {return _storage._totalExecs}
    set {_uniqueStorage()._totalExecs = newValue}
  }

  //// The average size of the corpus of this node and its child nodes.
  public var avgCorpusSize: Double {
    get {return _storage._avgCorpusSize}
    set {_uniqueStorage()._avgCorpusSize = newValue}
  }

  //// The average size of recently generated programs.
  public var avgProgramSize: Double {
    get {return _storage._avgProgramSize}
    set {_uniqueStorage()._avgProgramSize = newValue}
  }

  //// The average size of programs recently added to the corpus.
  public var avgCorpusProgramSize: Double {
    get {return _storage._avgCorpusProgramSize}
    set {_uniqueStorage()._avgCorpusProgramSize = newValue}
  }

  //// The average execution time of recently generated and successfully executed programs in seconds.
  public var avgExecutionTime: Double {
    get {return _storage._avgExecutionTime}
    set {_uniqueStorage()._avgExecutionTime = newValue}
  }

  //// The current number of executions per second.
  public var execsPerSecond: Double {
    get {return _storage._execsPerSecond}
    set {_uniqueStorage()._execsPerSecond = newValue}
  }

  //// The average fraction of the total time that is not spent executing programs in the target engine.
  public var fuzzerOverhead: Double {
    get {return _storage._fuzzerOverhead}
    set {_uniqueStorage()._fuzzerOverhead = newValue}
  }

  //// The average fraction of recent executions spent on minimization.
  public var minimizationOverhead: Double {
    get {return _storage._minimizationOverhead}
    set {_uniqueStorage()._minimizationOverhead = newValue}
  }

  //// The number of child nodes connected directly or indirectly to this instance, i.e. the size of the (sub-)tree rooted at this instance.
  public var numChildNodes: UInt64 {
    get {return _storage._numChildNodes}
    set {_uniqueStorage()._numChildNodes = newValue}
  }

  //// The percentage of edges covered if doing coverage-guided fuzzing.
  public var coverage: Double {
    get {return _storage._coverage}
    set {_uniqueStorage()._coverage = newValue}
  }

  //// The correctness rate of recently generated programs (number of valid programs divided by number of generated programs).
  public var correctnessRate: Double {
    get {return _storage._correctnessRate}
    set {_uniqueStorage()._correctnessRate = newValue}
  }

  //// The timeout rate of recently generated programs (number of timeouts divided by number of generated programs).
  public var timeoutRate: Double {
    get {return _storage._timeoutRate}
    set {_uniqueStorage()._timeoutRate = newValue}
  }

  //// The number of samples that reached at least one target (AFLGo directed fuzzing).
  public var targetReachingSamples: UInt64 {
    get {return _storage._targetReachingSamples}
    set {_uniqueStorage()._targetReachingSamples = newValue}
  }

  //// The average number of pre-target seeds.
  public var avgPreTargetSeeds: Double {
    get {return _storage._avgPreTargetSeeds}
    set {_uniqueStorage()._avgPreTargetSeeds = newValue}
  }

  //// The average number of post-target seeds.
  public var avgPostTargetSeeds: Double {
    get {return _storage._avgPostTargetSeeds}
    set {_uniqueStorage()._avgPostTargetSeeds = newValue}
  }

  public var avgPreTargetSeedAge: Double {
    get {return _storage._avgPreTargetSeedAge}
    set {_uniqueStorage()._avgPreTargetSeedAge = newValue}
  }

  public var maxPreTargetSeedAge: UInt64 {
    get {return _storage._maxPreTargetSeedAge}
    set {_uniqueStorage()._maxPreTargetSeedAge = newValue}
  }

  public var minPreTargetSeedAge: UInt64 {
    get {return _storage._minPreTargetSeedAge}
    set {_uniqueStorage()._minPreTargetSeedAge = newValue}
  }

  public var midPreTargetSeedAge: UInt64 {
    get {return _storage._midPreTargetSeedAge}
    set {_uniqueStorage()._midPreTargetSeedAge = newValue}
  }

  public var avgPostTargetSeedAge: Double {
    get {return _storage._avgPostTargetSeedAge}
    set {_uniqueStorage()._avgPostTargetSeedAge = newValue}
  }

  public var maxPostTargetSeedAge: UInt64 {
    get {return _storage._maxPostTargetSeedAge}
    set {_uniqueStorage()._maxPostTargetSeedAge = newValue}
  }

  public var minPostTargetSeedAge: UInt64 {
    get {return _storage._minPostTargetSeedAge}
    set {_uniqueStorage()._minPostTargetSeedAge = newValue}
  }

  public var midPostTargetSeedAge: UInt64 {
    get {return _storage._midPostTargetSeedAge}
    set {_uniqueStorage()._midPostTargetSeedAge = newValue}
  }

  //// The success rate of minimizations for the last 1000 interesting samples.
  public var minimizationSuccessRate: Double {
    get {return _storage._minimizationSuccessRate}
    set {_uniqueStorage()._minimizationSuccessRate = newValue}
  }

  //// The average minimization iterations over the last 1000 samples.
  public var minimizationIterationAvg: Double {
    get {return _storage._minimizationIterationAvg}
    set {_uniqueStorage()._minimizationIterationAvg = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "fuzzilli.protobuf"

extension Fuzzilli_Protobuf_LogMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "origin"),
    2: .same(proto: "level"),
    3: .same(proto: "label"),
    4: .same(proto: "content"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.origin) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.level) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.content) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.origin.isEmpty {
      try visitor.visitSingularStringField(value: self.origin, fieldNumber: 1)
    }
    if self.level != 0 {
      try visitor.visitSingularUInt32Field(value: self.level, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Fuzzilli_Protobuf_LogMessage, rhs: Fuzzilli_Protobuf_LogMessage) -> Bool {
    if lhs.origin != rhs.origin {return false}
    if lhs.level != rhs.level {return false}
    if lhs.label != rhs.label {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Fuzzilli_Protobuf_FuzzerState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FuzzerState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "corpus"),
    2: .same(proto: "evaluatorState"),
    3: .same(proto: "isWasmEnabled"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.corpus) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.evaluatorState) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isWasmEnabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.corpus.isEmpty {
      try visitor.visitSingularBytesField(value: self.corpus, fieldNumber: 1)
    }
    if !self.evaluatorState.isEmpty {
      try visitor.visitSingularBytesField(value: self.evaluatorState, fieldNumber: 2)
    }
    if self.isWasmEnabled != false {
      try visitor.visitSingularBoolField(value: self.isWasmEnabled, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Fuzzilli_Protobuf_FuzzerState, rhs: Fuzzilli_Protobuf_FuzzerState) -> Bool {
    if lhs.corpus != rhs.corpus {return false}
    if lhs.evaluatorState != rhs.evaluatorState {return false}
    if lhs.isWasmEnabled != rhs.isWasmEnabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Fuzzilli_Protobuf_Statistics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Statistics"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "totalSamples"),
    2: .same(proto: "validSamples"),
    3: .same(proto: "interestingSamples"),
    4: .same(proto: "timedOutSamples"),
    5: .same(proto: "crashingSamples"),
    6: .same(proto: "totalExecs"),
    7: .same(proto: "avgCorpusSize"),
    8: .same(proto: "avgProgramSize"),
    9: .same(proto: "avgCorpusProgramSize"),
    10: .same(proto: "avgExecutionTime"),
    11: .same(proto: "execsPerSecond"),
    12: .same(proto: "fuzzerOverhead"),
    13: .same(proto: "minimizationOverhead"),
    14: .same(proto: "numChildNodes"),
    15: .same(proto: "coverage"),
    16: .same(proto: "correctnessRate"),
    17: .same(proto: "timeoutRate"),
    18: .same(proto: "targetReachingSamples"),
    19: .same(proto: "avgPreTargetSeeds"),
    20: .same(proto: "avgPostTargetSeeds"),
    21: .same(proto: "avgPreTargetSeedAge"),
    22: .same(proto: "maxPreTargetSeedAge"),
    23: .same(proto: "minPreTargetSeedAge"),
    24: .same(proto: "midPreTargetSeedAge"),
    25: .same(proto: "avgPostTargetSeedAge"),
    26: .same(proto: "maxPostTargetSeedAge"),
    27: .same(proto: "minPostTargetSeedAge"),
    28: .same(proto: "midPostTargetSeedAge"),
    29: .same(proto: "minimizationSuccessRate"),
    30: .same(proto: "minimizationIterationAvg"),
  ]

  fileprivate class _StorageClass {
    var _totalSamples: UInt64 = 0
    var _validSamples: UInt64 = 0
    var _interestingSamples: UInt64 = 0
    var _timedOutSamples: UInt64 = 0
    var _crashingSamples: UInt64 = 0
    var _totalExecs: UInt64 = 0
    var _avgCorpusSize: Double = 0
    var _avgProgramSize: Double = 0
    var _avgCorpusProgramSize: Double = 0
    var _avgExecutionTime: Double = 0
    var _execsPerSecond: Double = 0
    var _fuzzerOverhead: Double = 0
    var _minimizationOverhead: Double = 0
    var _numChildNodes: UInt64 = 0
    var _coverage: Double = 0
    var _correctnessRate: Double = 0
    var _timeoutRate: Double = 0
    var _targetReachingSamples: UInt64 = 0
    var _avgPreTargetSeeds: Double = 0
    var _avgPostTargetSeeds: Double = 0
    var _avgPreTargetSeedAge: Double = 0
    var _maxPreTargetSeedAge: UInt64 = 0
    var _minPreTargetSeedAge: UInt64 = 0
    var _midPreTargetSeedAge: UInt64 = 0
    var _avgPostTargetSeedAge: Double = 0
    var _maxPostTargetSeedAge: UInt64 = 0
    var _minPostTargetSeedAge: UInt64 = 0
    var _midPostTargetSeedAge: UInt64 = 0
    var _minimizationSuccessRate: Double = 0
    var _minimizationIterationAvg: Double = 0

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _totalSamples = source._totalSamples
      _validSamples = source._validSamples
      _interestingSamples = source._interestingSamples
      _timedOutSamples = source._timedOutSamples
      _crashingSamples = source._crashingSamples
      _totalExecs = source._totalExecs
      _avgCorpusSize = source._avgCorpusSize
      _avgProgramSize = source._avgProgramSize
      _avgCorpusProgramSize = source._avgCorpusProgramSize
      _avgExecutionTime = source._avgExecutionTime
      _execsPerSecond = source._execsPerSecond
      _fuzzerOverhead = source._fuzzerOverhead
      _minimizationOverhead = source._minimizationOverhead
      _numChildNodes = source._numChildNodes
      _coverage = source._coverage
      _correctnessRate = source._correctnessRate
      _timeoutRate = source._timeoutRate
      _targetReachingSamples = source._targetReachingSamples
      _avgPreTargetSeeds = source._avgPreTargetSeeds
      _avgPostTargetSeeds = source._avgPostTargetSeeds
      _avgPreTargetSeedAge = source._avgPreTargetSeedAge
      _maxPreTargetSeedAge = source._maxPreTargetSeedAge
      _minPreTargetSeedAge = source._minPreTargetSeedAge
      _midPreTargetSeedAge = source._midPreTargetSeedAge
      _avgPostTargetSeedAge = source._avgPostTargetSeedAge
      _maxPostTargetSeedAge = source._maxPostTargetSeedAge
      _minPostTargetSeedAge = source._minPostTargetSeedAge
      _midPostTargetSeedAge = source._midPostTargetSeedAge
      _minimizationSuccessRate = source._minimizationSuccessRate
      _minimizationIterationAvg = source._minimizationIterationAvg
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._totalSamples) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._validSamples) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._interestingSamples) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._timedOutSamples) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._crashingSamples) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._totalExecs) }()
        case 7: try { try decoder.decodeSingularDoubleField(value: &_storage._avgCorpusSize) }()
        case 8: try { try decoder.decodeSingularDoubleField(value: &_storage._avgProgramSize) }()
        case 9: try { try decoder.decodeSingularDoubleField(value: &_storage._avgCorpusProgramSize) }()
        case 10: try { try decoder.decodeSingularDoubleField(value: &_storage._avgExecutionTime) }()
        case 11: try { try decoder.decodeSingularDoubleField(value: &_storage._execsPerSecond) }()
        case 12: try { try decoder.decodeSingularDoubleField(value: &_storage._fuzzerOverhead) }()
        case 13: try { try decoder.decodeSingularDoubleField(value: &_storage._minimizationOverhead) }()
        case 14: try { try decoder.decodeSingularUInt64Field(value: &_storage._numChildNodes) }()
        case 15: try { try decoder.decodeSingularDoubleField(value: &_storage._coverage) }()
        case 16: try { try decoder.decodeSingularDoubleField(value: &_storage._correctnessRate) }()
        case 17: try { try decoder.decodeSingularDoubleField(value: &_storage._timeoutRate) }()
        case 18: try { try decoder.decodeSingularUInt64Field(value: &_storage._targetReachingSamples) }()
        case 19: try { try decoder.decodeSingularDoubleField(value: &_storage._avgPreTargetSeeds) }()
        case 20: try { try decoder.decodeSingularDoubleField(value: &_storage._avgPostTargetSeeds) }()
        case 21: try { try decoder.decodeSingularDoubleField(value: &_storage._avgPreTargetSeedAge) }()
        case 22: try { try decoder.decodeSingularUInt64Field(value: &_storage._maxPreTargetSeedAge) }()
        case 23: try { try decoder.decodeSingularUInt64Field(value: &_storage._minPreTargetSeedAge) }()
        case 24: try { try decoder.decodeSingularUInt64Field(value: &_storage._midPreTargetSeedAge) }()
        case 25: try { try decoder.decodeSingularDoubleField(value: &_storage._avgPostTargetSeedAge) }()
        case 26: try { try decoder.decodeSingularUInt64Field(value: &_storage._maxPostTargetSeedAge) }()
        case 27: try { try decoder.decodeSingularUInt64Field(value: &_storage._minPostTargetSeedAge) }()
        case 28: try { try decoder.decodeSingularUInt64Field(value: &_storage._midPostTargetSeedAge) }()
        case 29: try { try decoder.decodeSingularDoubleField(value: &_storage._minimizationSuccessRate) }()
        case 30: try { try decoder.decodeSingularDoubleField(value: &_storage._minimizationIterationAvg) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._totalSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._totalSamples, fieldNumber: 1)
      }
      if _storage._validSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._validSamples, fieldNumber: 2)
      }
      if _storage._interestingSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._interestingSamples, fieldNumber: 3)
      }
      if _storage._timedOutSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timedOutSamples, fieldNumber: 4)
      }
      if _storage._crashingSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._crashingSamples, fieldNumber: 5)
      }
      if _storage._totalExecs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._totalExecs, fieldNumber: 6)
      }
      if _storage._avgCorpusSize.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgCorpusSize, fieldNumber: 7)
      }
      if _storage._avgProgramSize.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgProgramSize, fieldNumber: 8)
      }
      if _storage._avgCorpusProgramSize.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgCorpusProgramSize, fieldNumber: 9)
      }
      if _storage._avgExecutionTime.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgExecutionTime, fieldNumber: 10)
      }
      if _storage._execsPerSecond.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._execsPerSecond, fieldNumber: 11)
      }
      if _storage._fuzzerOverhead.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._fuzzerOverhead, fieldNumber: 12)
      }
      if _storage._minimizationOverhead.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._minimizationOverhead, fieldNumber: 13)
      }
      if _storage._numChildNodes != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._numChildNodes, fieldNumber: 14)
      }
      if _storage._coverage.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._coverage, fieldNumber: 15)
      }
      if _storage._correctnessRate.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._correctnessRate, fieldNumber: 16)
      }
      if _storage._timeoutRate.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._timeoutRate, fieldNumber: 17)
      }
      if _storage._targetReachingSamples != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._targetReachingSamples, fieldNumber: 18)
      }
      if _storage._avgPreTargetSeeds.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgPreTargetSeeds, fieldNumber: 19)
      }
      if _storage._avgPostTargetSeeds.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgPostTargetSeeds, fieldNumber: 20)
      }
      if _storage._avgPreTargetSeedAge.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgPreTargetSeedAge, fieldNumber: 21)
      }
      if _storage._maxPreTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._maxPreTargetSeedAge, fieldNumber: 22)
      }
      if _storage._minPreTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._minPreTargetSeedAge, fieldNumber: 23)
      }
      if _storage._midPreTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._midPreTargetSeedAge, fieldNumber: 24)
      }
      if _storage._avgPostTargetSeedAge.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._avgPostTargetSeedAge, fieldNumber: 25)
      }
      if _storage._maxPostTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._maxPostTargetSeedAge, fieldNumber: 26)
      }
      if _storage._minPostTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._minPostTargetSeedAge, fieldNumber: 27)
      }
      if _storage._midPostTargetSeedAge != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._midPostTargetSeedAge, fieldNumber: 28)
      }
      if _storage._minimizationSuccessRate.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._minimizationSuccessRate, fieldNumber: 29)
      }
      if _storage._minimizationIterationAvg.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._minimizationIterationAvg, fieldNumber: 30)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Fuzzilli_Protobuf_Statistics, rhs: Fuzzilli_Protobuf_Statistics) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._totalSamples != rhs_storage._totalSamples {return false}
        if _storage._validSamples != rhs_storage._validSamples {return false}
        if _storage._interestingSamples != rhs_storage._interestingSamples {return false}
        if _storage._timedOutSamples != rhs_storage._timedOutSamples {return false}
        if _storage._crashingSamples != rhs_storage._crashingSamples {return false}
        if _storage._totalExecs != rhs_storage._totalExecs {return false}
        if _storage._avgCorpusSize != rhs_storage._avgCorpusSize {return false}
        if _storage._avgProgramSize != rhs_storage._avgProgramSize {return false}
        if _storage._avgCorpusProgramSize != rhs_storage._avgCorpusProgramSize {return false}
        if _storage._avgExecutionTime != rhs_storage._avgExecutionTime {return false}
        if _storage._execsPerSecond != rhs_storage._execsPerSecond {return false}
        if _storage._fuzzerOverhead != rhs_storage._fuzzerOverhead {return false}
        if _storage._minimizationOverhead != rhs_storage._minimizationOverhead {return false}
        if _storage._numChildNodes != rhs_storage._numChildNodes {return false}
        if _storage._coverage != rhs_storage._coverage {return false}
        if _storage._correctnessRate != rhs_storage._correctnessRate {return false}
        if _storage._timeoutRate != rhs_storage._timeoutRate {return false}
        if _storage._targetReachingSamples != rhs_storage._targetReachingSamples {return false}
        if _storage._avgPreTargetSeeds != rhs_storage._avgPreTargetSeeds {return false}
        if _storage._avgPostTargetSeeds != rhs_storage._avgPostTargetSeeds {return false}
        if _storage._avgPreTargetSeedAge != rhs_storage._avgPreTargetSeedAge {return false}
        if _storage._maxPreTargetSeedAge != rhs_storage._maxPreTargetSeedAge {return false}
        if _storage._minPreTargetSeedAge != rhs_storage._minPreTargetSeedAge {return false}
        if _storage._midPreTargetSeedAge != rhs_storage._midPreTargetSeedAge {return false}
        if _storage._avgPostTargetSeedAge != rhs_storage._avgPostTargetSeedAge {return false}
        if _storage._maxPostTargetSeedAge != rhs_storage._maxPostTargetSeedAge {return false}
        if _storage._minPostTargetSeedAge != rhs_storage._minPostTargetSeedAge {return false}
        if _storage._midPostTargetSeedAge != rhs_storage._midPostTargetSeedAge {return false}
        if _storage._minimizationSuccessRate != rhs_storage._minimizationSuccessRate {return false}
        if _storage._minimizationIterationAvg != rhs_storage._minimizationIterationAvg {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
